# Generated by Django 4.0 on 2021-12-23 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='city',
            new_name='City',
        ),
    ]
