# Generated by Django 4.0 on 2021-12-23 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_rename_city_person_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='district',
            old_name='city',
            new_name='City',
        ),
        migrations.RenameField(
            model_name='states',
            old_name='city',
            new_name='City',
        ),
    ]
