# Generated by Django 4.0 on 2021-12-24 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_rename_city_district_city_rename_city_states_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='district',
            name='City',
        ),
        migrations.RemoveField(
            model_name='district',
            name='country',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='States',
            new_name='states',
        ),
        migrations.RemoveField(
            model_name='person',
            name='City',
        ),
        migrations.RemoveField(
            model_name='person',
            name='District',
        ),
        migrations.RemoveField(
            model_name='states',
            name='City',
        ),
        migrations.RemoveField(
            model_name='states',
            name='District',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='District',
        ),
    ]
