# Generated by Django 4.0 on 2021-12-24 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_district_person_district'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('District', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.district')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.country')),
                ('states', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.states')),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='db.city'),
        ),
    ]
