# Generated by Django 4.0 on 2021-12-24 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0006_city_person_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='country',
        ),
        migrations.RemoveField(
            model_name='city',
            name='states',
        ),
        migrations.RemoveField(
            model_name='district',
            name='country',
        ),
    ]
